Resources:
  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ${self:provider.environment.table_pk}
          AttributeType: "S"
        - AttributeName: ${self:provider.environment.table_sk}
          AttributeType: "S"
      KeySchema:
        - AttributeName: ${self:provider.environment.table_pk}
          KeyType: "HASH"
        - AttributeName: ${self:provider.environment.table_sk}
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: ${self:provider.environment.table_name}