service: saveToDDBService
frameworkVersion: '3'

plugins:
  - serverless-iam-roles-per-function
  - serverless-prune-plugin
  - serverless-offline

provider:
  name: aws
  runtime: ruby3.2
  stage: prod
  region: ap-south-1
  environment:
      table_name: payloads_table

custom:
  prune:
    automatic: true
    number: 3

functions:
  save:
    handler: handler.my_ddb_service
    memorySize: 256
    timeout: 30
    logRetentionInDays: 30
    iamRoleStatementsName: saveToDDBServiceRole
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItems
        Resource:
          - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/payloads_table
    events:
        - http:
            path: /dynamodb/{proxy+}
            method: post
            cors:
              origin: "*"
              headers:
                - x-api-key
              allowCredentials: true
              # Caches on browser and proxy for 10 minutes and doesnt allow proxy to serve out of date content
              cacheControl: "max-age=600, s-maxage=600, proxy-revalidate"