service: MyDDBService
frameworkVersion: '3'

plugins:
  - serverless-iam-roles-per-function
  - serverless-prune-plugin
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: ruby3.2
  stage: prod
  region: ap-south-1
  environment:
      table_name: my_json_table
      table_pk: year
      table_sk: unique_id

custom:
  prune:
    automatic: true
    number: 3
functions:
  - ${file(functions.yml)}

resources:
 - ${file(cloud-formation.yml)}
